version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "qi-traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:5050"
      - "--entrypoints.phpmyadmin.address=:4040"

      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=dreidekoost@gmail.com"
      - "--certificatesresolvers.le.acme.storage=./letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
      - "127.0.0.1:5050:5050"
      - "127.0.0.1:4040:4040"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=traefik"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"

      ############ MIDDLEWARE ###############
      # rate limiting 
      - "traefik.http.middlewares.limit.ratelimit.average=20"
      - "traefik.http.middlewares.limit.ratelimit.burst=10"

      # Basic authentication test:test
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
    volumes:
      - "./services/traefik/:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    container_name: qi-node
    build:
      context: ../update/
    volumes:
      - ../update/:/usr/src/app
    command: /usr/src/app/entrypoint.sh
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.qi-websecure.rule=Host(`update.qitech.de${DOMAIN_SUFFIX}`, `www.update.qitech.de${DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.qi-websecure.tls=true"
      - "traefik.http.routers.qi-websecure.entrypoints=websecure"
      - traefik.http.routers.qi-websecure.tls.certresolver=le

      - "traefik.http.routers.qi-web.rule=Host(`update.qitech.de${DOMAIN_SUFFIX}`, `www.update.qitech.de${DOMAIN_SUFFIX}`)"
      - "traefik.http.routers.qi-web.entrypoints=web"

      - "traefik.http.services.qi-node.loadbalancer.server.port=5000"
  

  database:
    image: mysql:5.7
    container_name: qi-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_RANDOM_ROOT_PASSWORD: ok # printed to log
      TZ: Europe/Amsterdam
    volumes:
      - dbdata:/var/lib/mysql
      - ./services/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: qi-phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
    volumes:
      - ./services/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

      - "traefik.http.routers.phpmyadmin.middlewares=auth"

volumes:
  dbdata: