name: Build Firmware

on:
  push:
    branches:
      - master
    paths:
      - esp/src/**
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e esp32dev
      working-directory: ./esp
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./esp/.pio/build/esp32dev/firmware.bin
        retention-days: 30
