name: Platform IO Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the esp folder of master branch
  push:
    branches:
      - master
    paths:
      - esp/src/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Firmware build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e esp32dev
      working-directory: ./esp
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: frimware.zip
        path: ./esp/.pio/build/esp32dev/firmware.bin
        retention-days: 30
