name: Release Spiffs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New Release Version vx.x.xs'
        required: true

jobs:
  buildSpiffs:
    name: Build Filesystem image
    uses: QiTech-Industries/Winder/.github/workflows/spiffs.yml@master
  upload:
    needs: buildSpiffs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: spiffs
        path: ./
    - name: Upload Build to DB
      uses: fjogeleit/http-request-action@master 
      with:
        url: 'https://update.qitech.de/firmware'
        method: 'POST'
        bearerToken: ${{ secrets.UPDATE_QITECH_DE }}
        data: '{ "version": "${{ github.event.inputs.version }}", "type": "spiffs" }'
        files: '{ "file": "${{ github.workspace }}/spiffs.bin" }'
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.6
      with:
        custom_tag: ${{ github.event.inputs.version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: SPIFFS ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
