# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Spiffs
on:
  push:
    branches:
      - master
    paths:
      - client/src/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
defaults:
  run:
    working-directory: client

jobs:
  build:
    name: Build Spiffs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    - run: npm install
    - run: npm run build
    - run: wget -c https://github.com/earlephilhower/mklittlefs/releases/download/3.0.0/x86_64-linux-gnu-mklittlefs-295fe9b.tar.gz -O - | tar -xz
    - run: ./mklittlefs -c ./build -p 256 -b 4096 -s 1507328 spiffs.bin
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: spiffs.zip
        path: spiffs.bin
        retention-days: 30
